from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog, name='catalog'),
    path('master-classes/', views.master_classes, name='master_classes'),
    path('organization/', views.organization, name='organization'),
    path('signup/', views.signup_masterclass, name='signup'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('add-post/', views.add_post, name='add_post'),
    path('edit-post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete-post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('add-category/', views.add_category, name='add_category'),
    path('edit-category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete-category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('add-product/', views.add_product, name='add_product'),
    path('edit-product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add-masterclass/', views.add_masterclass, name='add_masterclass'),
    path('edit-masterclass/<int:masterclass_id>/', views.edit_masterclass, name='edit_masterclass'),
    path('delete-masterclass/<int:masterclass_id>/', views.delete_masterclass, name='delete_masterclass'),
    path('buy/<int:product_id>/', views.buy_product, name='buy_product'),
    path('api/masterclass/<int:masterclass_id>/participants/',
         views.order_masterclass_participants,
         name='masterclass_participants'),
    path('api/order/<int:order_id>/details/',
         views.order_details,
         name='order_details'),
]