# Generated by Django 6.0.4 on 2026-05-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='MasterClassImage',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
