# Generated by Django 6.0.4 on 2026-05-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_productimage_product_delete_masterclassimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='master_classes/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='master_classes/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='master_classes/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='master_classes/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='master_classes/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='master_classes/', verbose_name='Изображение'),
        ),
    ]
